language: node_js
node_js:
- "10"

cache:
  directories:
  - node_modules

branches:
  only:
  - master

script:
- npm run build -- wallet
- npm run build -- explorer
- npm test

before_deploy:
- npm run build -- wallet --prod

deploy:
- provider: s3
  skip_cleanup: true
  region: eu-west-1
  bucket: tn-lto-wallet
  local_dir: dist/wallet
  on:
    branch: master
