language: node_js
node_js:
- "10"

cache:
  directories:
  - node_modules

branches:
  only:
  - master

script:
- npm test

before_deploy:
- npm run build -- --prod

deploy:
- provider: s3
  access_key_id: AKIAJQQQ7NJVV6B67VCA
  skip_cleanup: true
  secret_access_key:
    secure: "DpmJlW4qwrXIP/jXm8iwteEQ/wv3dz7/4uSQfchaBUJpduEUStTl1r91jC6XGzIR7cewf+uTpfqxaCzcL/ztEaNBKnjxNop9YDgShMSjpGI0fpb/W9nBOn7YJRWMxWnlhi2TarHsp1rX25S4SGJRCODcqzE2xQv6gNx1J2LOZPaLP/usFhIJKU/rCCKmUSVq1Za3zrP1FNkSvbFOlLBCp0hIc6Vj3vfjHCeGddNxBPMRcQaOa1ysb0WG2vFSSwdL8xko3NOgewD7ENDtc4Ju9Dzi8SJLroxOZ85gQIYHDO4EgSpIog52Gu9GBw54LZ+J+zyJdkA161QQIBxKuVjqV0d2u0n8bwXYA15GUPJk11Yu8K40Wi124uor9xpEXWmnd5r8gYxf2es+g3iFtL0/bR8sOvU4I/tJmt8LLhmF2Yej99XDhtwUM8PLUjJcbFku2u0QMkgT3Jcrb3YYVU5ich+W+BTQ2C8g0l0tVoTE1qPyctWwPX48XRqsApg0Bd92ssPklQAz9hvzJyfqKNgAcUJ8s9x+FJKyMiK/ZqreQQ/8TrbVRwqpKNg+sdjO5O2IwqhwFbmmN3C0XKjLLuWjc1p4noBaSYa7Uq+WiNfXIXaxmXU8DbV0ymO3oyx73Dl2NCCU+jfv5A38vlXr1k9LRkaI66iBtRD8HsWuoYCeZCs="
  region: eu-west-1
  bucket: tn-lto-wallet
  local_dir: dist
  on:
    branch: master
